
- name: configuration
  hosts: smartek
  vars_files:
    - vars.yml
  become: true
  become_method: sudo
  
  tasks:
  - name: Replace MongoDB config file
    copy:
      src: ./mongod.conf
      dest: /etc/mongod.conf
      owner: root
      group: root
      mode: '0644'
    
#if DNS_existing (var in varfiles) (DNSmapping entre hostname et n  true do not apply / if else apply  
  - name: Replace hosts file
    copy:
      src: ./hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'


  - name: Open MongoDB port #var in var files
    firewalld:
      port: "{{ port }}"
      permanent: yes
      state: enabled
    notify: Reload firewalld

  # - name: Generate private key
  #   openssl_privatekey:
  #     path: /path/to/private.key
  #     size: 2048
  #   register: private_key

  # - name: Generate certificate signing request (CSR)
  #   openssl_csr:
  #     path: /path/to/csr.pem
  #     privatekey_path: /path/to/private.key
  #     common_name: example.com
  #     subject_alt_name: "ops1.smartek.ae, ops2.smartek.ae"
  #   register: csr

  # - name: Generate self-signed certificate
  #   openssl_certificate:
  #     path: /path/to/certificate.crt
  #     privatekey_path: /path/to/private.key
  #     csr_path: /path/to/csr.pem
  #     provider: selfsigned
  #     days: 365
  #   register: certificate

  handlers:
  
    - name: Reload firewalld
      firewalld:
        state: reloaded
