
- name: configuration
  hosts: smartek
  vars_files:
    - vars.yml
  become: true
  become_method: sudo
  
  tasks:
  - name: Replace MongoDB config file
    copy:
      src: ./mongod.conf
      dest: /etc/mongod.conf
      owner: root
      group: root
      mode: '0644'
    notify: restart mongod    
    
#if DNS_existing var in varfiles DNSmapping entre hostname et n  true do not apply / if else apply  
  - name: Replace hosts file
    copy:
      src: ./hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'


  - name: Open MongoDB port #var in var files
    firewalld:
      port: "{{ mongo_port }}"
      permanent: yes
      state: enabled
    notify: Reload firewalld

  handlers:
  
    - name: Reload firewalld
      firewalld:
        state: reloaded
 
    - name: restart mongod
      systemd:
        name: mongod
        state: restarted
        enabled: true