- name: installation mongo
  hosts: smartek

  
  tasks:

  - name: Add MongoDB repo to yum repos
    yum_repository:
      name: mongodb-enterprise-6.0
      description: MongoDB Enterprise Repository
      baseurl: https://repo.mongodb.com/yum/redhat/$releasever/mongodb-enterprise/6.0/$basearch/
      gpgcheck: true
      gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc
      enabled: true
      state: present

  - name: Install MongoDB
    ansible.builtin.yum:
      name: mongodb-enterprise
      state: present
    notify: enable mongod
  
  handlers:
    - name: enable mongod
      systemd:
        name: mongod
        state: started
        enabled: true  
