- name: mongoshell playbook
  hosts: ops1.smartek.ae
  become: true
  become_method: sudo
  
  tasks:

  - name: Install MongoDB Shell
    command: ansible-galaxy collection install community.mongodb.mongodb_shell
    