- name: mongoshell playbook
  hosts: ops1.smartek.ae
  become: true
  become_method: sudo
  
  tasks:





  - name: Install MongoDB Shell
      yum:
        name: mongodb-shell
        state: present


- name: Run mongosh command
  shell: mongosh --host rs1/ops1.smartek.ae:27017,ops2.smartek.ae:27017,ops3.smartek.ae:27017 --eval --quiet

- name: Run mongosh command
  command: mongosh --host rs1/ops1.smartek.ae:27017,ops2.smartek.ae:27017,ops3.smartek.ae:27017

