
- name: Ops manager Install & Config
  hosts: ops2.smartek.ae, ops3.smartek.ae
  vars_files:
    - vars.yml
  become: true
  become_method: sudo
  
  tasks:


  - name: Download Ops Manager RPM package
    get_url:
      url: "{{ opsmanager_rmp_url }}"
      dest: /home/ops2/opsmanager.rpm

  - name: Install Ops Manager
    yum:
      name: /home/ops2/opsmanager.rpm
      state: present
      disable_gpg_check: yes

  - name: Open Ops Manager port
    firewalld:
      port: "{{ opsmanager_port }}"
      permanent: yes
      immediate: yes
      state: enabled
    notify: reload firewalld

  - name: Replace Ops Manager config file
    copy:
      src: ./conf-mms.properties
      dest: /opt/mongodb/mms/conf/conf-mms.properties
      owner: root
      group: root
      mode: '0644'

  - name: enable opsmanager
    systemd:
      name: mongodb-mms
      state: started
      enabled: true
  
  - name: Remove file
    ansible.builtin.file:
      path: /etc/mongodb-mms/gen.key
      state: absent

  - name: Copy gen key to /etc/mongodb-mms
    ansible.builtin.copy:
      src: /home/ops2/gen.key
      dest: /etc/mongodb-mms/

  - name: Change ownership of /etc/mongodb-mms
    file:
      path: /etc/mongodb-mms
      owner: mongodb-mms
      group: mongodb-mms
      recurse: yes

  handlers:
   - name: reload firewalld
     systemd:
      name: firewalld
      state: reloaded