
- name: Ops manager Install & Config
  hosts: ops1.smartek.ae
  vars_files:
    - vars.yml
  become: true
  become_method: sudo
  
  tasks:


  # - name: Download Ops Manager RPM package
  #   get_url:
  #     url: "{{ opsmanager_rmp_url }}"
  #     dest: /home/ops2/opsmanager.rpm

  # - name: Install Ops Manager
  #   yum:
  #     name: /home/ops2/opsmanager.rpm
  #     state: present
  #     disable_gpg_check: yes

  # - name: Open Ops Manager port
  #   firewalld:
  #     port: "{{ opsmanager_port }}"
  #     permanent: yes
  #     immediate: yes
  #     state: enabled
  #   notify: reload firewalld




  # - name: Replace Ops Manager config file
  #   copy:
  #     src: ./conf-mms.properties
  #     dest: /opt/mongodb/mms/conf/conf-mms.properties
  #     owner: root
  #     group: root
  #     mode: '0644'

  # - name: enable opsmanager
  #   systemd:
  #     name: mongodb-mms
  #     state: started
  #     enabled: true
  
  - name: Change ownership of /etc/mongodb-mms
    file:
      path: /etc/mongodb-mms
      owner: ops2
      group: ops2
      recurse: yes
  
  - name: Copy gen.key file
    copy:
      src: /etc/mongodb-mms/gen.key
      dest: /home/ops2/
      owner: ops2
      group: ops2
      mode: '0600'

  - name: Copy file using scp to ops2.smartek.ae
    ansible.builtin.copy:
      src: /home/ops2/file.txt
      dest: /etc/mongodb-mms/
    delegate_to: ops2.smartek.ae

  - name: Copy file using scp to ops3.smartek.ae
    ansible.builtin.copy:
      src: /home/ops2/file.txt
      dest: /etc/mongodb-mms/
    delegate_to: ops3.smartek.ae

  # handlers:
  #  - name: reload firewalld
  #    systemd:
  #     name: firewalld
  #     state: reloaded