- name: MongoDB Production Notes
  hosts: smartek 
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
  - name: Check AVX support
    command: "grep -o avx /proc/cpuinfo"
    register: avx_check


  - name: Fail playbook if AVX is not supported
    fail:
      msg: "AVX is not supported. Playbook execution halted."
    when: avx_check.stdout == ""

  - name: Set swappiness to 1
    sysctl:
      name: vm.swappiness
      value: 1
      state: present
      reload: yes

  
  - name: Create redahead service file
    template:
      src: redahead.service.j2
      dest: /etc/systemd/system/redahead.service
    vars:
      redahead_value: 8
    notify: enable redahead

  - name: Add lines to limits.conf
    lineinfile:
      path: /etc/security/limits.conf
      line: "{{ item }}"
      insertafter: EOF
    with_items:
      - "mongod  hard  fsize  unlimited"
      - "mongod  soft  fsize  unlimited"
      - "mongod  hard  cpu  unlimited"
      - "mongod  soft  cpu  unlimited"
      - "mongod  hard  as  unlimited"
      - "mongod  soft  as  unlimited"
      - "mongod  hard  memlock  unlimited"
      - "mongod  soft  memlock  unlimited"
      - "mongod  hard  nofile  64000"
      - "mongod  soft  nofile  64000"
      - "mongod  hard  noproc  64000"
      - "mongod  soft  noproc  64000"
    notify: restart mongod


  - name: Create disable-transparent-huge-pages service file
    copy:
      content: |
        [Unit]
        Description=Disable Transparent Huge Pages (THP)
        DefaultDependencies=no
        After=sysinit.target local-fs.target
        Before=mongod.service

        [Service]
        Type=oneshot
        ExecStart=/bin/sh -c 'echo never | tee /sys/kernel/mm/transparent_hugepage/enabled > /dev/null'

        [Install]
        WantedBy=basic.target
      dest: /etc/systemd/system/disable-transparent-huge-pages.service
    notify: enable disabling THP

  - name: Install numactl package
    yum:
      name: numactl
      state: present

  - name: Disable zone reclaim
    sysctl:
      name: vm.zone_reclaim_mode
      value: 0
      sysctl_set: yes
      state: present

  handlers:
 
    - name: restart mongod
      systemd:
        name: mongod
        state: restarted
        enabled: true
    
    - name: enable disabling THP
      systemd:
        name: disable-transparent-huge-pages.service
        state: started
        enabled: true
    - name: enable redahead
      systemd:
        name: redahead.service
        state: started
        enabled: true
  

